Repository eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt, pull requests merged in 2024-07, with the labels that each got.

#164 Upgrade gradlew to 8.8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#166 Upgrade to Kotlin 2
  build.gradle.kts
  gradle/libs.versions.toml
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/TestContext.kt
Labels: dependencies

#172 Upgrade to gradlew 8.9
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: documentation

#174 Upgrade dependencyCheck
  gradle/libs.versions.toml
Labels: dependencies, github_actions

#176 OpenAPI for Verifier endpoint
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierEndpointApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/SwaggerUi.kt
  src/main/resources/application.properties
  src/main/resources/public/openapi.json
  src/main/resources/static/index.html
  src/main/resources/templates/swagger-ui.html
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/StaticContentRouterTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/SwaggerUiTest.kt
Labels: documentation, feature, improvement

#177 Query for presentation event log
  README.md
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/VerifierApi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletApi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/persistence/PresentationInMemoryRepo.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetJarmJwks.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetPresentationDefinition.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetPresentationEvents.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetRequestObject.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransaction.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/TimeoutPresentations.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/persistence/LoadPresentationEvents.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/persistence/PresentationEvent.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/persistence/PublishPresentationEvent.kt
  src/main/resources/public/openapi.json
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/TestContext.kt
Labels: feature
