Repository eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt, pull requests merged in 2024-03, with the labels that each got.

#126 Update presentation exchange to 0.2.0
  gradle/libs.versions.toml
Labels: java

#127 Fix incorrect x5c JARs header claim
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/TestContext.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/SignRequestObjectNimbusTest.kt
  src/test/resources/test-cert.jks
Labels: bug

#128 Remove snapshot repo from gradle
  build.gradle.kts
Labels: github action

#132 Remove dokka plugin
  build.gradle.kts
  gradle/libs.versions.toml
Labels: build script

#135 Bump presentation-exchange version to 0.2.1
  gradle/libs.versions.toml
Labels: feature
