Repository eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt, pull requests merged in 2025-07, with the labels that each got.

#382 Do not require 'apv' be equal to 'nonce' when JARM encryption is used
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/VerifyJarmEncryptedJwtNimbus.kt
Labels: feature

#383 Upgrade SD-JWT library to v0.14.2
  gradle/libs.versions.toml
Labels: dependencies

#384 Add a configuration property to allow disabling Json Schema validations for SD-JWT VCs
  README.md
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/resources/application.properties
Labels: feature

#392 Upgrade eudi-lib-jvm-sdjwt-kt to 0.14.3
  gradle/libs.versions.toml
Labels: bug, dependencies

#344 Remove media/type vc+sd-jwt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/metadata/Formats.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/presentation/ValidateSdJwtVcOrMsoMdocVerifiablePresentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/sdjwtvc/SdJwtVcValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransaction.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/RetrieveRequestObject.kt
  src/test/resources/07-ehicSdJwtVc-presentationDefinition.json
  src/test/resources/07-ehicSdJwtVc-presentationSubmission.json
Labels: openid4vp alignment, v1

#404 Add accepting unencrypted auth error response for direct_post.jwt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostJwtTest.kt
Labels: feature, openid4vp alignment, v1

#410 Remove `/ui/clientMetadata` API
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/VerifierApi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetClientMetadata.kt
  src/main/resources/public/openapi.json
Labels: other

#411 Update DCQL classes
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/DCQL.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransaction.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/RetrieveRequestObject.kt
  src/test/resources/00-dcql.json
  src/test/resources/02-dcql.json
  src/test/resources/03-dcql.json
  src/test/resources/04-dcql.json
  src/test/resources/05-dcql.json
Labels: openid4vp alignment, v1, breaks public api

#413 Draft changes for vp formats supported
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/CreateJarNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/JWSAlgorithmStringSerializer.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/json/JacksonSupport.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/metadata/Formats.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/presentation/ValidateSdJwtVcOrMsoMdocVerifiablePresentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/VerifierConfig.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransaction.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/RetrieveRequestObject.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/presentation/ValidateVerifiablePresentation.kt
  src/main/resources/application.properties
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/TestContext.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransactionTest.kt
Labels: openid4vp alignment, v1

#415 Use correct names for Wallet metadata properties, and remove deprecated ones
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/VerifierConfig.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/RetrieveRequestObject.kt
Labels: bug
