Repository eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt, pull requests merged in 2025-02, with the labels that each got.

#249 Remove deprecated `presentation_id` property.
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransaction.kt
Labels: other

#252 Introduce per Presentation `response_uri`.
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletApi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetPresentationEvents.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletApiClient.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostJwtTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostWithIdTokenAndVpTokenTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostWithIdTokenTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransactionTest.kt
Labels: feature, improvement

#250 Ignore unknown properties in MSO instances
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/Cbor.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/DeviceResponseValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/DocumentValidator.kt
  src/main/resources/trusted-issuers.jks
Labels: bug

#241 Improve vp_token parsing and validations
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/json/JsonPathReader.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/presentation/ValidateSdJwtVcOrMsoMdocVerifiablePresentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/Presentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetPresentationEvents.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/ValidateMsoMdocDeviceResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/ValidateSdJwtVc.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/presentation/ValidateVerifiablePresentation.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostJwtTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostTest.kt
  src/test/resources/02-presentationSubmission.json
  src/test/resources/03-presentationSubmission.json
  src/test/resources/04-dcql.json
  src/test/resources/05-dcql.json
  src/test/resources/06-pidPlusMdl-presentationDefinition.json
  src/test/resources/06-pidPlusMdl-presentationSubmission.json
  src/test/resources/06-pidPlusMdl-vpToken.json
Labels: improvement

#246 Support for Transaction Data
  README.md
  build.gradle.kts
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/digest/Hash.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/encoding/Base64.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/RequestObject.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/SignRequestObjectNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/json/JsonPathReader.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/json/JsonSupport.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/presentation/ValidateSdJwtVcOrMsoMdocVerifiablePresentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/DCQL.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/Presentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/TransactionData.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/VerifierConfig.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransaction.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/presentation/ValidateVerifiablePresentation.kt
  src/main/resources/application.properties
  src/main/resources/public/openapi.json
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransactionTest.kt
Labels: feature, openid4vp alignment, draft22

#259 Update library dependencies
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: dependencies

#265 Display in Swagger-UI the version of OpenId4VP supported.
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/SwaggerUi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/DCQL.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/OpenId4VPSpec.kt
  src/main/resources/application.properties
  src/main/resources/i18n/messages.properties
  src/main/resources/public/css/style.css
  src/main/resources/templates/swagger-ui.html
Labels: feature, improvement

#273 Introduce `vp_formats` in Client Metadata
  README.md
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/VerifierApi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/SignRequestObjectNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/json/JsonSupport.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/metadata/Formats.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/presentation/ValidateSdJwtVcOrMsoMdocVerifiablePresentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/Presentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/VerifierConfig.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetClientMetadata.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransaction.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/presentation/ValidateVerifiablePresentation.kt
  src/main/resources/application.properties
  src/main/resources/public/openapi.json
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/TestContext.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostJwtTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostWithIdTokenAndVpTokenTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransactionTest.kt
  src/test/resources/02-presentationSubmission.json
  src/test/resources/03-presentationSubmission.json
  src/test/resources/04-dcql.json
  src/test/resources/05-dcql.json
  src/test/resources/06-pidPlusMdl-presentationDefinition.json
Labels: bug, openid4vp alignment
