Repository eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt, pull requests merged in 2025-03, with the labels that each got.

#279 Introduce a Spring Profile that activates Ktor HttpClients that trust self-signed certificates and disables hostname verification.
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
Labels: feature

#284 Handle gracefully JARM validation failures.
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetPresentationEvents.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/PostWalletResponse.kt
Labels: improvement

#294 Removed JWKs by Reference for JARM
  README.md
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletApi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/SignRequestObjectNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/VerifierConfig.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetJarmJwks.kt
  src/main/resources/application.properties
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/TestContext.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/SignRequestObjectNimbusTest.kt
Labels: openid4vp alignment, draft22

#288 Add support for `request_uri_method` POST.
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletApi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/CreateJarNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/EncryptionRequirement.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/JarmSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/OpenId4VPSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/Presentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/RFC8414.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/RFC9101.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/VerifierConfig.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/GetRequestObject.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransaction.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/RetrieveRequestObject.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/jose/CreateJar.kt
  src/main/resources/application.properties
  src/main/resources/public/openapi.json
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/TestContext.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/PresentationDefinitionTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletApiClient.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/jose/CreateJarNimbusTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransactionTest.kt
Labels: feature, openid4vp alignment, draft 21
