Repository eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt, pull requests merged in 2025-06, with the labels that each got.

#366 Fixed expired credential in authlete example
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/ExamplesTest.kt
Labels: bug

#316 Trusted issuers per docType/vct with LOTL support
  README.md
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/timer/RefreshTrustSources.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/cert/TrustSources.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/lotl/FetchLOTLCertificatesDSS.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/DeviceResponseValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/DocumentValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/presentation/ValidateSdJwtVcOrMsoMdocVerifiablePresentation.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/sdjwtvc/SdJwtVcValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/domain/VerifierConfig.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/ValidateMsoMdocDeviceResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/out/lotl/FetchLOTLCertificates.kt
  src/main/resources/application.properties
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/WalletResponseDirectPostJwtTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/lotl/FetchLOTLCertificatesDSSTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/DeviceResponseValidatorTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/ExamplesTest.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/mso/IssueCheck.kt
  src/test/kotlin/eu/europa/ec/eudi/verifier/endpoint/port/input/InitTransactionTest.kt
Labels: feature

#373 Feat/sd jwt vc type metadata resolution
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierEndpointApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/input/web/UtilityApi.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/sdjwtvc/LookupTypeMetadataFromUrl.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/sdjwtvc/SdJwtVcValidator.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/sdjwtvc/SdJwtVerificationExceptionExtensions.kt
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/adapter/out/sdjwtvc/ValidateJsonSchema.kt
  src/main/resources/application.properties
  src/main/resources/public/openapi.json
Labels: feature

#378 Fix incorrect Type Metadata env. variables
  README.md
Labels: documentation

#380 Introduce a cache for `ResolveTypeMetadata`
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/verifier/endpoint/VerifierContext.kt
  src/main/resources/application.properties
Labels: feature
